### ISSUE TITLE
d10.2.3

### ISSUE THREAD

**Issue by limelect** [casbin4d/Casbin4D#2]
make it work in d10.2 also and down

[dcc32 Error] Casbin.Policy.pas(604): E2010 Incompatible types: 'TStringDynArray' and 'System.TArray<System.string>'

**Comment by jkour** [comment]
TStringDynArray changed definition in 10.3 and that's what causes the error.

I didn't have 10.2 installed on my PC but installed it yesterday. I will prepare a package for 10.2 soon

**Comment by jkour** [comment]
New version released. Package for D 10.2 added.

Please test and report back if anything
